### ISSUE TITLE
Release tag to latest commit

### ISSUE THREAD

**Issue by ihor-sviziev** [quafzi/magento-performance-tweaks#6]
Please add release commit to have ability install latest version it via composer.

**Comment by tim-bezhashvyly** [comment]
I don't think it's a good idea to install such a module with composer. Definitely not all tweaks will be applicable to your store so fair share of modifications may be required.

**Comment by ihor-sviziev** [comment]
@tim-bezhashvyly BTW if you have many modifications you will check all changes to fix possible conflicts. We just installed this module and few our websites started works really faster. I think just run "composer update" is really good solution, why not?

**Comment by tim-bezhashvyly** [comment]
Because modifying files in `vendor` dir is a no-no :wink:

**Comment by ihor-sviziev** [comment]
@tim-bezhashvyly If you want something change - you can create fork and porform required modifications there.

**Comment by tim-bezhashvyly** [comment]
You are absolutely right.

**Comment by quafzi** [comment]
Sorry for the delay. The latest release now is 1.0.0. Please take care: its composer package name now is `firegento/performance-tweaks`!
