### ISSUE TITLE
Turn this extension into a FireGento extension

### ISSUE THREAD

**Issue by quafzi** [quafzi/magento-performance-tweaks#9]
We need to

* fix some coding style issues according to https://github.com/firegento/phpcs
* move it into Firegento namespace
* Change license to [GNU General Public License, version 3 (GPLv3)](http://opensource.org/licenses/gpl-3.0)

**Comment by quafzi** [comment]
To be able change the license, I need contributors to agree to this license change!

@erfanimani 
@jeroenvermeulen 
@tim-bezhashvyly

**Comment by tim-bezhashvyly** [comment]
Do whatever you want. Thank you for asking.

**Comment by jeroenvermeulen** [comment]
I agree, say hi to @daim2k5 from me :-)

**Comment by erfanimani** [comment]
Agreed :)

**Comment by quafzi** [comment]
@therouv Go :)
